feat: add number of faulty commits to the output to the action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,11 +1,16 @@
-name: 'check-conventional-commits'
-description: 'Checks if all the commits (of the branch which triggered the event) comply to the conventional commits standard'
+name: "check-conventional-commits"
+description: "Checks if all the commits (of the branch which triggered the event) comply to the conventional commits standard"
 author: Alex Speranza
 
 inputs:
   token:
-    description: 'Personal access token with pull permissions on repository'
+    description: "Personal access token with pull permissions on repository"
     required: true
+
+outputs:
+  errors:
+    description: "Number of non conventional commit messages"
+    value: ${{ steps.run-script.outputs.errors }}
 
 runs:
   using: "composite"
@@ -14,7 +19,10 @@ runs:
       with:
         fetch-depth: 0
         token: ${{ inputs.token }}
-    - run: >
-        test "$(git log --grep='^\w+(\((\w|-)+\))?!?: .+$' --invert-grep -E --pretty=format:%s | awk 'END {print NR}')" -eq "0"
+    - id: run-script
+      run: |
+        set -euo pipefail
+        ERRORS="$(git log --grep='^\w+(\((\w|-)+\))?!?: .+$' --invert-grep -E --pretty=format:%s | awk 'END {print NR}')"
+        echo "errors=$ERRORS" >> "$GITHUB_OUTPUT"
+        test "$ERRORS" -eq "0"
       shell: bash
-
