fix: move logic inside action instead of script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,15 +1,15 @@
-name: 'check-conventional-commits'
-description: 'Checks if all the commits (of the branch which triggered the event) comply to the conventional commits standard'
+name: "check-conventional-commits"
+description: "Checks if all the commits (of the branch which triggered the event) comply to the conventional commits standard"
 author: Alex Speranza
 
 inputs:
   token:
-    description: 'Personal access token with pull permissions on repository'
+    description: "Personal access token with pull permissions on repository"
     required: true
 
 outputs:
   errors:
-    description: 'Number of non conventional commit messages'
+    description: "Number of non conventional commit messages"
     value: ${{ steps.run-script.outputs.errors }}
 
 runs:
@@ -20,7 +20,9 @@ runs:
         fetch-depth: 0
         token: ${{ inputs.token }}
     - id: run-script
-      run: >
-        test "$(./script.sh)" -eq "0"
+      run: |
+        set -euo pipefail
+        ERRORS="$(git log --grep='^\w+(\((\w|-)+\))?!?: .+$' --invert-grep -E --pretty=format:%s | awk 'END {print NR}')"
+        echo "errors=$ERRORS" >> "$GITHUB_OUTPUT"
+        test "$ERRORS" -eq "0"
       shell: bash
-
